### ISSUE TITLE
End unanswered calls

### ISSUE THREAD

**Issue by pravinjohn** [bkdev98/react-native-incoming-call#1]
Hi,
How can I end unanswered or missed calls?

**Comment by bkdev98** [comment]
The server could send a timeout message (using firebase background) then in app use `IncomingCall.dismiss();`

**Comment by pravinjohn** [comment]
> The server could send a timeout message (using firebase background) then in app use `IncomingCall.dismiss();`

But that doesn't finish the activity though.. I added a BroadcastReceiver to make it work.

**Comment by bkdev98** [comment]
Fixed in v2.0.2
