### ISSUE TITLE
How to open MainActivity instead of UnlockScreenActivity

### ISSUE THREAD

**Issue by kimho** [bkdev98/react-native-incoming-call#14]
In the current version, UnlockScreenActivity pops up when a call comes in while the app is in the background.
But I want the default MainActivity to be launched, not the UnlockScreenActivity.
In that case, it seems that the incoming screen can be customized with RN javascript code.
How can I make MainActivity run instead of UnlockScreenActivity?

**Comment by bkdev98** [comment]
This library not designed to do this behavior but I believed `openAppFromHeadlessMode` & `backToForeground ` could also get the job done. So instead call `IncomingCall.display` you could use `openAppFromHeadlessMode` to wake the app and then `getExtrasFromHeadlessMode` to determine what to do.

**Comment by kimho** [comment]
@bkdev98 
Thank you for answer. When I use IncomingCall.backToForeground() it works the way I want.
