### ISSUE TITLE
Call screen keeps running until any action is taken

### ISSUE THREAD

**Issue by MadCoderme** [bkdev98/react-native-incoming-call#16]
There should be a time limit until which the call screen will be shown. After that, it will disappear. I tried to set a timeout function with `IncomingCall.dismiss()` but it doesn't work.
Please help me to solve this issue

**Comment by bkdev98** [comment]
I wasn't so sure but it seems like `setTimeout` will not working properly in backgroundHandler. I'll try to add a timeout param or something later. Also I found https://github.com/jamesisaac/react-native-background-task looks promising but not sure if it could use with this package.

**Comment by MadCoderme** [comment]
How can I manage it to close the screen after an interval right now?

**Comment by bkdev98** [comment]
Fixed in 2.0.3. Now you can pass the fifth parameter of IncomingCall.display as the timeout in ms to dismiss the call screen.
