### ISSUE TITLE
Answer call button does not open app in background

### ISSUE THREAD

**Issue by Lekxel** [bkdev98/react-native-incoming-call#4]
Hi, I am really grateful to have this great package.
But the issue am facing is the when you click on the answer button when the app is in background, it doesn't open the app.

**Comment by bkdev98** [comment]
Hi, what device you're using?

**Comment by Lekxel** [comment]
Infinix (android 9).
Tried on another phone, still same issue

**Comment by anjandaffo** [comment]
Same issue I am facing. @Lekxel are you got any workaround for this?

**Comment by Lekxel** [comment]
The workaround I got is using https://github.com/lvlrSajjad/react-native-launch-application

So, when the answer event is received, I try to launch the app first and handle last received notification

**Comment by bkdev98** [comment]
I just released version 2 of the library which believed fixed this bug so I gonna close it here. Feel free to reopen or create new issue if you still got this issue.
