### ISSUE TITLE
Incoming call screen not called if the app is killed

### ISSUE THREAD

**Issue by eskiesirius** [bkdev98/react-native-incoming-call#6]

**Comment by bkdev98** [comment]
I just released version 2 of the library which believed fixed this bug so I gonna close it here. Feel free to reopen or create new issue if you still got this issue.

**Comment by msaidm** [comment]
Incoming call screen not called if the app is killed in Andriod version 10

**Comment by bkdev98** [comment]
To make it works in android 10 you need to grant this permission first: [https://www.npmjs.com/package/rn-android-overlay-permission](https://www.npmjs.com/package/rn-android-overlay-permission)
