### ISSUE TITLE
IncomingCall.dismiss() is not working

### ISSUE THREAD

**Issue by Lekxel** [bkdev98/react-native-incoming-call#9]
I tried to end unanswered calls using IncomingCall.dismiss(), but it doesnt work at all.

**Comment by Lekxel** [comment]
@bkdev98 Thanks for the big update on this version 2. 
I'd like to know if this has been fixed as well.

**Comment by bkdev98** [comment]
I forgot this one 😅 Will try to fix asap.

**Comment by Lekxel** [comment]
Great, thanks

**Comment by bkdev98** [comment]
I done a quick fix for this issue in v2.0.2, please have a check.

**Comment by Lekxel** [comment]
Okay, great,I will check and give you feedback.
Thanks for the great work.

**Comment by bkdev98** [comment]
Hi @Lekxel, thank you for testing this update and for the suggestions. I created two issues for those enhancements and going to close this issue.
